language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.4
      env: TOX_ENV=py34
    - python: 2.7
      env: TOX_ENV=py27

install: pip install tox

script: tox -e $TOX_ENV

branches:
  only:
    - master
